Include the required units of the Forchheimer IPR model
ESSS/barril pull request #120
Opened 2023-05-31 20:07 UTC by caio-ramos

ASIM-5275

Adds specific units employed in the Forchheimer IPR model. A new category and quantity type is defined for linear and quadratic parameters.

2023-06-01 10:04 UTC, nicoddemus requested changes
Nice!

Please update the CHANGELOG with the new units. :+1:

2023-06-01 14:38 UTC, caio-ramos commented on src/barril/units/posc.py
> +        "Pa2/scm.s",
You're 100% right. The corrections have been made.

2023-06-01 14:41 UTC, nicoddemus approved these changes

2023-06-02 13:05 UTC, ggrbill approved these changes
Good Job!

2023-06-02 13:05 UTC, ggrbill commented on src/barril/units/_tests/test_posc.py
> +    assert default.GetValue("Pa2.d/scm") == approx(1.1574074074074073e-05)
`sm6` also sounds awkward to me. 
Let's use `scm2`. It looks simpler and cleaner.

2023-06-02 15:56 UTC, Gualcar approved these changes

2023-06-02 19:31 UTC, closed without merging